-- INSERTING YOUTUBE VIDEOS --5XisXVcbZEw fJa1DMVB0vc
-- Run BTS! 1-40 done 
-- inserting the videos 
INSERT INTO Videos (name, description, platformID, link, released, thumbnailID)
			VALUES	
    (
        "Run BTS! EP.5: 100 Seconds Sports Day",
        "MC: none\nTeams: none\nBTS compete against the show's crew members in Korean traditional games. They must complete six relay missions in 100 seconds. BTS win and the cameramen receive a drink punishment (water, vinegar, hot sauce and wasabi).",
        1,
        "https://www.youtube.com/embed/geqemGfLGl0",
        "2015-09-29",
        1
    ),
    (
        "Run BTS! EP.6: Confession (Part 1)",
        "MC: none\nTeams: Priest (Jimin) Penitents (V, Jungkook, J-Hope, & Suga)\nBTS participate in a skit where they confess their sins to priest Jimin",
        1,
        "https://www.youtube.com/embed/Q-rmawjwOyw",
        "2015-10-03",
        1
    ),
    (
        "Run BTS! EP.6: Confession (Part 2)",
        "MC: none\nTeams: Priest (Suga) Penitents (Jin, RM, & V)\nA continuation of the previous episode, the members now confess their sins to priest Suga",
        1,
        "https://www.youtube.com/embed/aPpxATzrCeM",
        "2015-10-20",
        1
    ),
    (
        "Run BTS! EP.7: Silmido Part 1, Survival",
        "MC: none\nTeams: Red Team (RM, Jin, V, & Jungkook) Black Team (Suga, J-Hope, & Jimin)\nBTS divide into teams and play paintball at a survival game center in Inje, Gangwon-do. Red Team wins",
        1,
        "https://www.youtube.com/embed/iSxvE82RC3o",
        "2015-11-16",
        1
    ),
    (
        "Run BTS! EP.8: Silmido Part 2, Find The Flag",
        "MC: none\nTeams: none\nA continuation of the previous episode, BTS engage in a treasure hunt for flags hidden in the mountains. The winners will receive dinner coupons RM, Jin, Jimin, V, and Jungkook successfully complete the challenge.",
        1,
        "https://www.youtube.com/embed/JgmGvoDnN4w",
        "2015-12-15",
        1
    ),
    (
        "Run BTS! EP.9: Silmido Part 3, Bungee Jumping",
        "MC: none\nTeams: Tall Team  (RM, Jin, V, & Jungkook) To-Be-Tall Team  (Suga, J-Hope, & Jimin)\nStill in Gangwon-do, BTS visit the Inje Bungee Jump facility next, the highest jump tower in South Korea (63m). They must each portray a song title using their body during their jump and the other members must correctly identify it All members successfully complete the challenge.",
        1,
        "https://www.youtube.com/embed/WkWLu-Awxf4",
        "2015-12-22",
        1
    ),
    (
        "Run BTS! EP.10: Silmido, SPY?!?",
        "MC: none\nTeams: none\nAt the end of their time in Gangwon-do, the members eat dinner together and try to figure out who the day's spy was they incorrectly choose V. Jungkook reveals himself as the spy and receives a cash prize for successfully completing seven of his nine assigned spy missions.",
        1,
        "https://www.youtube.com/embed/vh4arZ1Cz4Y",
        "2016-01-05",
        1
    ),
    (
        "Run BTS! EP.11: Back to School",
        "MC: none\nTeams: none\nBTS act out a skit in a school setting. Suga plays the role of a female exchange student and the other members attempt to charm her",
        1,
        "https://www.youtube.com/embed/VgzdortYQ6E",
        "2017-01-31",
        1
    ),
    (
        "Run BTS! EP.12: Cops",
        "MC: none\nTeams: Police Officers (RM, Suga, V & Jungkook) Prisoners (Jin, J-Hope & Jimin)\nBTS act out a skit where police officers interrogate prisoners for crimes that do not make sense",
        1,
        "https://www.youtube.com/embed/FWz81fmTpcQ",
        "2017-02-28",
        1
    ),
    (
        "Run BTS! EP.13: The Spy Who Returned (Part 1)",
        "MC: Suga\nTeams: Older Team (Jin, J-Hope & RM) Younger Team (Jimin, V & Jungkook)\nWhile at One Mount Water Park, the members must find out who is sabotaging them",
        1,
        "https://www.youtube.com/embed/pY2pDsEcwc0",
        "2017-03-07",
        1
    ),
    (
        "Run BTS! EP.14: The Spy Who Returned (Part 2)",
        "MC: Suga\nTeams: Older Team (Jin, J-Hope & RM) Younger Team (Jimin, V & Jungkook)\nWhile at One Mount Water Park, the members must find out who is sabotaging them",
        1,
        "https://www.youtube.com/embed/O9d5LwFfMLo",
        "2017-03-14",
        1
    ),
    (
        "Run BTS! EP.15: The Spy Who Returned (Part 3)",
        "MC: Suga\nTeams: Older Team (Jin, J-Hope & RM) Younger Team (Jimin, V & Jungkook)\nWhile at One Mount Water Park, the members must find out who is sabotaging them Jin wins. The other members must do what he says in order to receive food.",
        1,
        "https://www.youtube.com/embed/S00n5Qbn2aM",
        "2017-03-21",
        1
    ),
    (
        "Run BTS! EP.16: Snowpark Winter Olympics",
        "MC: none\nTeams: none\nThe members participate in a BTS Winter Olympics. J-Hope wins, followed by Jungkook and Jin in second and third place respectively.tation neede",
        1,
        "https://www.youtube.com/embed/WfaFI5PleA8",
        "2017-03-28",
        1
    ),
    (
        "Run BTS! EP.17: Arcade Olympics (Part 1)",
        "MC: none\nTeams: none\nThe members play games at an arcade.",
        1,
        "https://www.youtube.com/embed/rs_3CFHm4KI",
        "2017-04-11",
        1
    ),
    (
        "Run BTS! EP.18: Arcade Olympics (Part 2)",
        "MC: none\nTeams: none\nThe members play games at an arcade. RM wins. Suga, who ranked last overall, and Jimin, who ranked last in air hockey, both receive penalties: a balloon is popped right next to their ears.",
        1,
        "https://www.youtube.com/embed/bA35OcZ-pJk",
        "2017-04-18",
        1
    ),
    (
        "Run BTS! EP.19: Strike",
        "MC: none\nTeams: Jungkook V, Jimin, RM, J-Hope, Suga & Jin Jungkook, V & Jin Jimin, RM, J-Hope & Suga\nBTS go bowling Jungkook wins the first round. The other members have to bow to him. Jimin, RM, J-Hope & Suga win the second round. Jungkook, V & Jin have to bow to them and get spanked.",
        1,
        "https://www.youtube.com/embed/hUaCfzriU-E",
        "2017-05-02",
        1
    ),
    (
        "Run BTS! EP.20: The Taste of Korea",
        "MC: Jin\nTeams: Suga's Team (Suga, Jimin & V) Jungkook's Team (Jungkook, RM & J-Hope)\nThe members attempt to create a meal within an hour Suga's Team wins. Jungkook's Team has to clean up.",
        1,
        "https://www.youtube.com/embed/KvehOunyO70",
        "2017-05-23",
        1
    ),
    (
        "Run BTS! EP.21: Board Game Competition",
        "MC: none\nTeams: Team Chica (Suga, J-Hope & Jimin) Team Go (RM, Jin, V & Jungkook)\nBTS divide into groups and play board games. RM's Team wins. Jimin loses at Uno and receives a penalty.tation neede",
        1,
        "https://www.youtube.com/embed/JX3DXFwdnK4",
        "2017-05-30",
        1
    ),
    (
        "Run BTS! EP.22: Hangawi Festival",
        "MC: none\nTeams: Jin & Jimin Suga & V RM, J-Hope & Jungkook\nFor a Chuseok special, the members wear hanbok, make songpyeon, and play traditional Korean games RM, J-Hope & Jungkook win. Suga and V each have to eat a random songpyeon.",
        1,
        "https://www.youtube.com/embed/7H75WKc6Zzk",
        "2017-10-03",
        1
    ),
    (
        "Run BTS! EP.23: Pet Friends",
        "MC: J-Hope\nTeams: none\nThe members pair up with dogs and compete in canine obedience and agility J-Hope with Nuri wins.",
        1,
        "https://www.youtube.com/embed/EsYZCrSWnGs",
        "2017-10-17",
        1
    ),
    (
        "Run BTS! EP.24: BTS vs. Zombies",
        "MC: none\nTeams: Team A (RM, V & Jungkook) Team B (Jin & Suga) Team C (J-Hope & Jimin)\nThe members fight off a zombie attack at Everland while going through an obstacle course and solving puzzles Team B wins",
        1,
        "https://www.youtube.com/embed/KLzWCC74itE",
        "2017-10-24",
        1
    ),
    (
        "Run BTS! EP.25: Game King",
        "MC: Suga\nTeams: Team Blue (RM, J-Hope & V) Team Red (Jin, Jimin & Jungkook)\nTwo teams compete in multiplayer games at a PC room Team Blue wins. Jimin loses the final race and has to sing Blood Sweat & Tears while being doused with water",
        1,
        "https://www.youtube.com/embed/9oNaPJYO10E",
        "2017-10-31",
        1
    ),
    (
        "Run BTS! EP.26: Secret Agent",
        "MC: none\nTeams: Team Kim Seok-jin (Jin, J-Hope & Jimin) Team A (Suga & V) Team kingsman (RM & Jungkook)\nThe members divide into groups and play a spy game Team Kim Seok-jin wins.",
        1,
        "https://www.youtube.com/embed/-yC7mMIU_m4",
        "2017-11-07",
        1
    ),
    (
        "Run BTS! EP.27: Welcome to Your First MT (Part 1)",
        "MC: none\nTeams: Team Ooh-Ah (J-Hope & Jimin) Team Ro-Jul (Suga & V) Team Kim Seok-jin (RM, Jin & Jungkook)\nBTS divide into teams and play games to win food for a barbecue",
        1,
        "https://www.youtube.com/embed/35KVt3jYNQU",
        "2017-11-14",
        1
    ),
    (
        "Run BTS! EP.28: Welcome to Your First MT (Part 2)",
        "MC: none\nTeams: Team Ooh-Ah (J-Hope & Jimin) Team Ro-Jul (Suga & V) Team Kim Seok-jin (RM, Jin & Jungkook)\nMembers divide into teams and sing karaoke All teams win and enjoy a barbeque with the food they won. Team Ooh-Ah wins 300g of meat, rice and sausages. Team Ro-Jul wins instant rice. Team Kim Seok-jin wins sausages.",
        1,
        "https://www.youtube.com/embed/5sxzTiwOrCo",
        "2017-11-21",
        1
    ),
    (
        "Run BTS! EP.29: A Billboard Hot 100 Promise: Be Each Other's Stylist",
        "MC: Suga\nTeams: none\nBTS hold a fashion show. The members pick out clothes from their personal closets for the others to wear on the runway",
        1,
        "https://www.youtube.com/embed/f7AOsE55rtA",
        "2017-11-28",
        1
    ),
    (
        "Run BTS! EP.30: The Variety Show of Memories (Part 1",
        "MC: Suga\nTeams: Team Glasses (RM, V & Jungkook) Team Kim Seok-jin (Jin, J-Hope & Jimin)\nBTS play games from popular Korean variety shows of the past.",
        1,
        "https://www.youtube.com/embed/zvfGF96rpJM",
        "2017-12-05",
        1
    ),
    (
        "Run BTS! EP.31: The Variety Show of Memories (Part 2",
        "MC: Suga\nTeams: Team Glasses (RM, V & Jungkook) Team Kim Seok-jin (Jin, J-Hope & Jimin)\nBTS play games from popular Korean variety shows of the past Team Glasses wins. Team Kim Seok-jin has to wear retro fashion to the airport.",
        1,
        "https://www.youtube.com/embed/ElMSCtF7D58",
        "2017-12-12",
        1
    ),
    (
        "Run BTS! EP.32: Take Care of Santa",
        "MC: none\nTeams: none\nBTS participate in a Christmas special and complete various missions. J-Hope wins.tation neede",
        1,
        "https://www.youtube.com/embed/nJjlIbTbxUU",
        "2017-12-23",
        1
    ),
    (
        "Run BTS! EP.33: BTS and Manito (Part 1",
        "MC: none\nTeams: Jimin & V J-Hope & Jungkook RM Jin & Suga\nEach member is assigned a Manito and a mission they must complete in secret while playing various games",
        1,
        "https://www.youtube.com/embed/4lJAUxBpF-E",
        "2017-12-28",
        1
    ),
    (
        "Run BTS! EP.34: BTS and Manito (Part 2",
        "MC: none\nTeams: none\nEach member is assigned a Manito and a mission they must complete in secret while playing various games Jimin wins. Suga has to wear Jimin's BT21 costume, and Jin has to wear hanbok to the airport.",
        1,
        "https://www.youtube.com/embed/c1mXPOfXjJc",
        "2018-01-02",
        1
    ),
    (
        "Run BTS! EP.35: Kimchi Battle",
        "MC: none\nTeams: RM, Jin & V Suga & Jimin J-Hope & Jungkook\nBTS split into teams and compete to make the best kimchi using recipes from different parts of Korea J-Hope & Jungkook win.",
        1,
        "https://www.youtube.com/embed/T6oSrTKQpTU",
        "2018-01-09",
        1
    ),
    (
        "Run BTS! EP.36: Kimchi Wars",
        "MC: none\nTeams: Dance Line  (J-Hope, Jimin & Jungkook) Vocal Line  (RM, Jin, Suga & V)\nBTS use the kimchi they created in the previous episode to make a new dish. Vocal Line wins. Dance Line has to clean up.tation neede",
        1,
        "https://www.youtube.com/embed/OwpYJjCSe7M",
        "2018-01-16",
        1
    ),
    (
        "Run BTS! EP.37: BTS Marble Returns",
        "MC: none\nTeams: none\nBTS play the board game BTS Marble (previously played in Episode 28) Jin wins. RM has to climb Achasan mountain, and Suga has to write a book report.",
        1,
        "https://www.youtube.com/embed/Dn085oNuwk8",
        "2018-01-23",
        1
    ),
    (
        "Run BTS! EP.38: Spin BTS",
        "MC: none\nTeams: Golden Youngest (Jin & Jimin) Cherry RM (J-Hope & Jungkook) Happy Evangelist (RM, Suga & V)\nBTS divide into teams and play tug of war. They must pull two other members in order to complete a puzzle Golden Youngest wins. As the losers, RM gets blurred, Suga has to wear Jin's BT21 costume, and V has to accompany RM in climbing Achasan mountain.\n\n\nSuga carries out his punishment from episode 35 by wearing a Chimmy costume.",
        1,
        "https://www.youtube.com/embed/ZyayTHW1mcc",
        "2018-01-30",
        1
    ),
    (
        "Run BTS! EP.39: BTS Golden Bell, Pt. ",
        "MC: Jin\nTeams: RM, V & Jungkook Suga, J-Hope & Jimin\nBTS play various games through a Golden Bell-like show.",
        1,
        "https://www.youtube.com/embed/fx2Fyn4qlnE",
        "2018-02-06",
        1
    ),
    (
        "Run BTS! EP.40: Lunar New Year Special: Only Good Things",
        "MC: none\nTeams: Team 2018 (V, Jin & Suga) Team New Year (J-Hope, Jimin, RM & Jungkook)\nBTS play a series of Korean New Year games Team New Year wins. Team 2018 does not get to eat.",
        1,
        "https://www.youtube.com/embed/R7OYtymovXs",
        "2018-02-13",
        1
    ),
    (
        "Run BTS! EP.42: BTS Golden Bell, Pt. ",
        "MC: Jin\nTeams: RM, V & Jungkook Suga , J-Hope & Jimin\nIn a continuation of episode 40, BTS play various games in a Golden Bell-type show. RM wins. Suga loses the rock, paper, and scissor game and has to go to the sea.\n\n\nSuga carries out his punishment from episode 38 by presenting a book report",
        1,
        "https://www.youtube.com/embed/",
        "2018-02-20",
        1
    ),
    (
        "Run BTS! EP.43: Sports Challenge",
        "MC: none\nTeams: none\nBTS members individually compete in an obstacle course Jimin wins. J-Hope gets soaked with toy hat.",
        1,
        "https://www.youtube.com/embed/",
        "2018-02-27",
        1
    ),
    (
        "Run BTS! EP.44: Satisfaction of the Five Senses (Part 1)",
        "MC: none\nTeams: none\nThe members play games that test their senses\n\n\nSuga carries out his punishments from episodes 39 and 42 by going to the sea and wearing an RJ costume.",
        1,
        "https://www.youtube.com/embed/",
        "2018-03-06",
        1
    ),
    (
        "Run BTS! EP.45: Satisfaction of the Five Senses (Part 2)",
        "MC: none\nTeams: none\nThe members play games that test their senses. Jungkook wins. Jin has to make RM and V breakfast for their journey.\n\n\nRM and V carry out their punishment from episodes 38 and 39 by climbing Achasan mountain",
        1,
        "https://www.youtube.com/embed/",
        "2018-03-13",
        1
    ),
    (
        "Run BTS! EP.46: BTS Caf\u00e9",
        "MC: none\nTeams: none\nBTS compete against each other to make the best coffee Jin wins.",
        1,
        "https://www.youtube.com/embed/",
        "2018-03-20",
        1
    ),
    (
        "Run BTS! EP.47: BTS Workshop",
        "MC: none\nTeams: none\nBTS learn how to make pottery",
        1,
        "https://www.youtube.com/embed/",
        "2018-03-27",
        1
    ),
    (
        "Run BTS! EP.48: Protect the BTS Village (Part 1)",
        "MC: none\nTeams: BTS Villagers (Jungkook, RM, Jin & J-Hope) Blue Villagers (Jimin, Suga & V)\nBTS play a modified version of the social deduction game Mafia. The members act as residents of BTS Village and must protect the town by deducing who among them are imposters from the neighboring enemy Blue Village.tation neede\n\n\nEpisodes set in BTS Village make up the BTS Village universe (as explained in episode 146). Protect the BTS Village is followed by Season 3's Reply BTS Village (episodes 121-122) and BTS Village: Joseon Dynasty (episodes 146-148).",
        1,
        "https://www.youtube.com/embed/",
        "2018-04-03",
        1
    ),
    (
        "Run BTS! EP.49: Protect the BTS Village (Part 2)",
        "MC: none\nTeams: BTS Villagers (Jungkook, RM, Jin & J-Hope) Blue Villagers (Jimin, Suga & V)\nBTS play a modified version of Mafia Blue Villagers win.",
        1,
        "https://www.youtube.com/embed/",
        "2018-04-10",
        1
    ),
    (
        "Run BTS! EP.50: Eve Event, Pt. 1",
        "MC: Suga\nTeams: none\nBTS celebrate the eve of their 50th episode by reacting to highlights from the highest-ranked episodes and famous moments in the show\n\n\nI. Top 5 Run BTS Episodes by view count:\n\nEpisode 31 (The Variety Show of Memories Part 2)\nEpisode 11 (Back to School)\nEpisode 20 (The Taste of Korea)\nEpisode 33 (BTS and Manito Part 1)\nEpisode 12 (Cops)\nII. Top 5 Run BTS Episodes by Heart Count\n\nEpisode 31 (The Variety Show of Memories Part 2)\nEpisode 33 (BTS and Manito Part 1)\nEpisode 32 (Take Care of Santa)\nEpisode 34 (BTS and Manito Part 2)\nEpisode 35 (Kimchi Battle)",
        1,
        "https://www.youtube.com/embed/",
        "2018-04-17",
        1
    ),
    (
        "Run BTS! EP.51: Eve Event, Pt. 2 & The 50th Episode Special, Pt. 1",
        "MC: Suga\nTeams: The 50th Episode Special: Frogs (Jungkook & V) Rabbits (Jimin & Jin) Dogs (RM, J-Hope & Suga)\nI. Run BTS 50th Episode Eve Event, Pt. 2: BTS continue their 50th episode eve event with an award ceremony.\n\nCutie Pie Award (\uc7ac\uac04\ub465\uc774 \ubd80\ubb38) - Jimin (winner) Suga V (nominees)\nSports Award (\uc2a4\ud3ec\uce20 \ubd80\ubb38) - Jungkook (winner) RM Jimin (nominees)\nMC Award (\uc9c4\ud589 \ubd80\ubb38) - Suga (winner) Jin (nominee)\nActing Award (\uc0c1\ud669\uadf9 \ubd80\ubb38) - V (winner) J-Hope Jungkook (nominees)\nCooking Award (\uc694\ub9ac \ubd80\ubb38) - Jin (winner) J-Hope Jungkook (nominees)\nConsideration Award (\ubc30\ub824 \ubd80\ubb38) - RM (winner) Jungkook Jimin (nominees)\nAudio Award (\uc624\ub514\uc624 \ubd80\ubb38) - J-Hope (winner) Jin Suga (nominees)\nBest Chemistry Award (\ubca0\uc2a4\ud2b8 \ucf00\ubbf8\uc0c1) - Suga & V RM & Jin J-Hope, Jimin & Jungkook (winners)\nHonorary Grand Prize (\uba85\uc608\uc758 \ub300\uc0c1) - BTS (winners)\n\nII. The 50th Episode Special, Pt. 1: BTS celebrate their 50th episode and carry-out a mission in an amusement park",
        1,
        "https://www.youtube.com/embed/",
        "2018-04-24",
        1
    ),
    (
        "Run BTS! EP.52: The 50th Episode Special, Pt. ",
        "MC: Suga\nTeams: The 50th Episode Special: Frogs (Jungkook & V) Rabbits (Jimin & Jin) Dogs (RM, J-Hope & Suga)\nBTS celebrate their 50th episode and carry-out a mission in an amusement park. Dogs win a portable Ramen cooker.tation neede",
        1,
        "https://www.youtube.com/embed/",
        "2018-05-01",
        1
    ),
    (
        "Run BTS! EP.53: BTS Escape",
        "MC: none\nTeams: Sleeping Girl Team (Jin, Suga & V) Korean Dry Sauna Team (RM, J-Hope, Jimin & Jungkook)\nBTS divide into teams and must get out of an escape room. Sleeping Girl Team wins.tation neede",
        1,
        "https://www.youtube.com/embed/",
        "2018-06-26",
        1
    ),
    (
        "Run BTS! EP.54: BTS Picnic (Part 1",
        "MC: none\nTeams: none\nThe members go on a trip and shop for food items they will need. Jungkook wins. Jin and Jimin have to walk there.",
        1,
        "https://www.youtube.com/embed/",
        "2018-07-03",
        1
    ),
    (
        "Run BTS! EP.55: BTS Picnic (Part 2",
        "MC: none\nTeams: RM, Suga, J-Hope & Jimin Jin, V & Jungkook\nThe members go on a trip and compete in outdoor games.",
        1,
        "https://www.youtube.com/embed/",
        "2018-07-10",
        1
    ),
    (
        "Run BTS! EP.56: BTS Picnic (Part 3",
        "MC: none\nTeams: none\nThe members go on a trip and play board games Jungkook and J-Hope lose and have to cook dinner.",
        1,
        "https://www.youtube.com/embed/",
        "2018-07-17",
        1
    ),
    (
        "Run BTS! EP.57: BTS Picnic (Part 4)",
        "MC: none\nTeams: Team A (RM, Jimin & V) Team B (Jin & Suga) Team C (J-Hope & Jungkook)\nThe members go on a trip, sing karaoke, and read poems they wrote for each other Team B wins. The other teams have to clean up.",
        1,
        "https://www.youtube.com/embed/",
        "2018-07-24",
        1
    ),
    (
        "Run BTS! EP.58: BTS Chef (Part 1)",
        "MC: none\nTeams: 95's (V & Jimin) Boxing (Jungkook & Jin) Ref (J-Hope, Suga, & RM)\nBTS divide into groups and cook Italian food\n\n\nThis is the first episode to use Idol as the opening theme.",
        1,
        "https://www.youtube.com/embed/",
        "2019-01-01",
        1
    ),
    (
        "Run BTS! EP.59: BTS Chef (Part 2)",
        "MC: none\nTeams: 95's (V & Jimin) Boxing (Jungkook & Jin) Ref (J-Hope, Suga, & RM)\nBTS finish making their Italian dishes and are judged by a professional chef Ref team wins. Boxing and 95's tie for second place, and play rock paper scissors as a tie breaker. Boxing team wins, 95's have to clean up and make coffee for everyone.",
        1,
        "https://www.youtube.com/embed/",
        "2019-01-08",
        2
    ),
    (
        "Run BTS! EP.60: Run BTS in Hotel (Part 1)",
        "MC: none\nTeams: Team Kim Seok-jin (Suga, J-Hope, & Jungkook) Team Ppa (RM & Jin) Team Jji (Jimin & V)\nBTS divide into teams and play song-related games in a hotel room",
        1,
        "https://www.youtube.com/embed/",
        "2019-01-15",
        2
    ),
    (
        "Run BTS! EP.61: Run BTS in Hotel (Part 2)",
        "MC: none\nTeams: Team Kim Seok-jin (Suga, J-Hope, & Jungkook) Team Ppa (RM & Jin) Team Jji (Jimin & V)\nBTS continue playing games in a hotel room Team Kim Seok-jin wins. As a reward, members can yield their future penalties to another person.\n\n\nPenalty used in Episode 82",
        1,
        "https://www.youtube.com/embed/",
        "2019-01-22",
        2
    ),
    (
        "Run BTS! EP.62: BTS Sauna (Part 1)",
        "MC: none\nTeams: Team A (RM, J-Hope, V, & Jungkook) Team Kim Seok-jin (Jin, Suga, & Jimin)\nBTS play games at a sauna",
        1,
        "https://www.youtube.com/embed/",
        "2019-01-29",
        2
    ),
    (
        "Run BTS! EP.63: BTS Sauna (Part 2)",
        "MC: none\nTeams: Team A (RM, J-Hope, V, & Jungkook) Team Kim Seok-jin (Jin, Suga, & Jimin)\nBTS continue playing games at a sauna Team A wins. Team Kim Seok-jin gets splashed with water.",
        1,
        "https://www.youtube.com/embed/",
        "2019-02-05",
        2
    ),
    (
        "Run BTS! EP.64: BTS School (Part 1)",
        "MC: Suga\nTeams: Team Kim Seok-jin (RM, Jin, & V) Team Jeon Jungkook (J-Hope, Jimin, & Jungkook)\nBTS act as students in a classroom, led by teacher/MC Suga, and hold an election for class president Jungkook wins and is given a secret benefit\n\n\nBenefit revealed in Episode 65",
        1,
        "https://www.youtube.com/embed/",
        "2019-02-12",
        2
    ),
    (
        "Run BTS! EP.65: BTS School (Part 2)",
        "MC: Suga\nTeams: Team Kim Seok-jin (RM, Jin, & V) Team Jeon Jungkook (J-Hope, Jimin, & Jungkook)\nBTS use handbells to play a song during music class, play a game to win food for lunch period, and compete in physical games for PE class",
        1,
        "https://www.youtube.com/embed/",
        "2019-02-19",
        2
    ),
    (
        "Run BTS! EP.66: BTS School (Part 3)",
        "MC: Suga\nTeams: Team Kim Seok-jin (RM, Jin, & V) Team Jeon Jungkook (J-Hope, Jimin, & Jungkook)\nThe members  participate in a debate about mint-chocolate ice cream during Korean class while being sprayed with water Team Kim Seok-jin wins. For his class president benefit, Jungkook chooses Jin as the additional member to complete the punishment with the losing team: Team Jeon Jungkook, Suga, and Jin must watch the sunset in Incheon.",
        1,
        "https://www.youtube.com/embed/",
        "2019-02-26",
        2
    ),
    (
        "Run BTS! EP.67: BTS in a Comic Book Caf\u00e9 (Part 1)",
        "MC: none\nTeams: none\nBTS play games in a comic book cafe",
        1,
        "https://www.youtube.com/embed/",
        "2019-03-05",
        2
    ),
    (
        "Run BTS! EP.68: BTS in a Comic Book Caf\u00e9 (Part 2)",
        "MC: none\nTeams: none\nBTS continue playing games at a comic book cafe BTS lose, but they win 20 comic books in a bonus game.",
        1,
        "https://www.youtube.com/embed/",
        "2019-03-12",
        2
    ),
    (
        "Run BTS! EP.69: Heart Pang",
        "MC: none\nTeams: Team Seok-jin (RM, Jin, & Jungkook) Jimin & V Suga & J-Hope\nBTS play Heart Pang, a board game, in a hotel Suga & J-Hope win. Jimin and V have to wear a special outfit to the airport.",
        1,
        "https://www.youtube.com/embed/",
        "2019-03-19",
        2
    ),
    (
        "Run BTS! EP.70: BTS in Toronto (Part 1)",
        "MC: none\nTeams: none\nBTS visit Niagara Falls in Ontario, Canada for sightseeing and surprise missions. They stop at a Korean BBQ restaurant for lunch, then go grocery shopping for ingredients to make dinner",
        1,
        "https://www.youtube.com/embed/",
        "2019-04-30",
        2
    ),
    (
        "Run BTS! EP.71: BTS in Toronto (Part 2)",
        "MC: none\nTeams: none\nThe members shop for warmer clothes, then return to the rental house and choose their rooms for the night. RM, Suga, and J-Hope share one room. Jin, Jimin, V, and Jungkook share the other",
        1,
        "https://www.youtube.com/embed/",
        "2019-05-07",
        2
    ),
    (
        "Run BTS! EP.72: BTS in Toronto (Part 3)",
        "MC: none\nTeams: none\nJ-Hope and Jungkook fail the morning mission and have to cook breakfast for everyone. The members visit Lake Ontario. Jimin and Jungkook are the day's overall losers, having accumulated the least points from various missions. Jimin has to jump into the lake Jin accompanies him because of their friendship and buy clothes for Jin. Jungkook has to buy food for all of the staff",
        1,
        "https://www.youtube.com/embed/",
        "2019-05-14",
        2
    ),
    (
        "Run BTS! EP.73: BTS and Mafia",
        "MC: none\nTeams: X-Man (J-Hope) Pranksters (RM, Jin, Suga, Jimin, V & Jungkook)\nBTS members are given secret missions and prank J-Hope in a game of Mafia, while J-Hope attempts to make his team lose in all rounds of the game. All members lose. After a random pick between Jungkook and J-Hope, J-Hope has to accompany Jimin and V in wearing clothes designed by Jimin when they return to Korea",
        1,
        "https://www.youtube.com/embed/",
        "2019-05-21",
        2
    ),
    (
        "Run BTS! EP.74: Run BTS Drama (Part 1)",
        "MC: none\nTeams: none\nBTS test their acting skills by reenacting lines from famous TV dramas before shooting their own short film",
        1,
        "https://www.youtube.com/embed/",
        "2019-05-28",
        2
    ),
    (
        "Run BTS! EP.75: Run BTS Drama (Part 2",
        "MC: none\nTeams: none\nBTS assume the role of both cast members and film personnel and shoot various scenes for a short film. They must finish within two hours to avoid their bloopers from the recording being aired.",
        1,
        "https://www.youtube.com/embed/",
        "2019-06-04",
        2
    ),
    (
        "Run BTS! EP.76: Run BTS Drama (Part 3",
        "MC: none\nTeams: none\nBTS continue shooting their film under time constraints.",
        1,
        "https://www.youtube.com/embed/",
        "2019-06-11",
        2
    ),
    (
        "Run BTS! EP.77: Run BTS Drama (Part 4",
        "MC: none\nTeams: none\nBTS finish filming their scenes, and the final version of their short film, titled Dalbang Dorm (\ub2ec\ubc29\ud558\uc219, RR: Dalbanghasuk), is aired",
        1,
        "https://www.youtube.com/embed/",
        "2019-06-18",
        2
    ),
    (
        "Run BTS! EP.78: Food Guest (Part 1)",
        "MC: Jin\nTeams: Team Kim Seok-jin (J-Hope, Jimin, & V) Team Seok-jin Kim (RM, Suga, & Jungkook)\nBTS play multiple rounds of food guessing games to win lunch",
        1,
        "https://www.youtube.com/embed/",
        "2019-06-25",
        2
    ),
    (
        "Run BTS! EP.79: Food Guest (Part 2)",
        "MC: Jin\nTeams: Team Kim Seok-jin (J-Hope, Jimin, & V) Team Seok-jin Kim (RM, Suga, & Jungkook)\nBTS play three final rounds of food-related games. Team Seok-jin Kim wins. Team Kim Seok-jin has to wear rabbit hats at the airport in front of the press/media",
        1,
        "https://www.youtube.com/embed/",
        "2019-07-02",
        2
    ),
    (
        "Run BTS! EP.80: Operation 007 (Part 1)",
        "MC: none\nTeams: Upstairs (Suga, Jimin, & V) Downstairs (RM, Jin, J-Hope, & Jungkook)\nBTS search for cards hidden around Lotte Duty Free, which can be exchanged for chances to play mini-games to win paper hearts. The member with the most paper hearts at the end wins",
        1,
        "https://www.youtube.com/embed/",
        "2019-07-09",
        2
    ),
    (
        "Run BTS! EP.81: Operation 007 (Part 2)",
        "MC: none\nTeams: Upstairs (Suga, Jimin, & V) Downstairs (RM, Jin, J-Hope, & Jungkook)\nBTS continue searching for cards, play mini-games, and collect paper hearts. Jin wins and receives a set of gift cards worth  ₩1.4 million provided by Lotte Duty Free",
        1,
        "https://www.youtube.com/embed/",
        "2019-07-16",
        2
    ),
    (
        "Run BTS! EP.82: BTS VR (Part 1)",
        "MC: none\nTeams: Team V (Jimin, V, & Jungkook) Team R (RM, Jin, Suga, & J-Hope)\nBTS play four rounds of VR games. At the end of the competition, the team with the lowest score will receive a mysterious punishment",
        1,
        "https://www.youtube.com/embed/",
        "2019-07-23",
        2
    ),
    (
        "Run BTS! EP.83: BTS VR (Part 2)",
        "MC: none\nTeams: Team V (Jimin, V, & Jungkook) Team R (RM, Jin, Suga, & J-Hope)\nBTS continue playing VR games. Team V wins. Jin and Suga play a horror VR game for their penalty",
        1,
        "https://www.youtube.com/embed/",
        "2019-07-30",
        2
    ),
    (
        "Run BTS! EP.84: Summer Outing (Part 1)",
        "MC: none\nTeams: Team Muscat (Suga, Jimin, V, & Jungkook) Team Fresh (RM, Jin, & J-Hope)\nBTS play water polo and go water tubing while trying to answer math questions. Team Fresh wins both games",
        1,
        "https://www.youtube.com/embed/",
        "2019-08-06",
        2
    ),
    (
        "Run BTS! EP.85: Summer Outing (Part 2",
        "MC: none\nTeams: Team Muscat (Suga, Jimin, & V) Team Fresh (RM, Jin, & Jungkook)\nBTS play recreational games at a lake including water sliding, obstacle racing, and blob jumping. J-Hope experiences nausea and is replaced by Jungkook on Team Fresh. Team Muscat wins the first game, both teams lose the second, and Team Fresh wins the third.",
        1,
        "https://www.youtube.com/embed/",
        "2019-08-13",
        2
    ),
    (
        "Run BTS! EP.86: Summer Outing (Part 3)",
        "MC: none\nTeams: Chasers (Jin, Suga, RM, Jimin, & V) Defender (Jungkook)\nBTS play a bonus game of Defeat Jungkook, ride a boat, and exchange Manito gifts while relaxing and having dinner by the shore. All members win. Suga and J-Hope do not ride the boat due to motion sickness, but join later for dinner and to exchange gifts",
        1,
        "https://www.youtube.com/embed/",
        "2019-08-20",
        2
    ),
    (
        "Run BTS! EP.87: Hangul Day Special (Part 1)",
        "MC: none\nTeams: none\nIn celebration of Hangul Day, BTS are quizzed on Korean traditional words and phrases. They are awarded stickers based on their performance\n\n\nThis is the first episode made available on both V Live and Weverse.",
        1,
        "https://www.youtube.com/embed/",
        "2019-10-08",
        2
    ),
    (
        "Run BTS! EP.88: Hangul Day Special (Part 2",
        "MC: none\nTeams: none\nBTS search for Hangul letters hidden around Oil Tank Culture Park in Seoul, which can be made into words and exchanged for additional stickers. The members simultaneously attempt to tag their assigned target's back with stickers without getting caught.",
        1,
        "https://www.youtube.com/embed/",
        "2019-10-18",
        2
    ),
    (
        "Run BTS! EP.89: Hangul Day Special (Part 3",
        "MC: none\nTeams: none\nStill at Oil Tank Culture Park, the members simultaneously attempt to tag their assigned target's back with stickers without getting caught. V wins and is given a motor scooter as a prize.",
        1,
        "https://www.youtube.com/embed/",
        "2019-10-22",
        2
    ),
    (
        "Run BTS! EP.90: BTS Gayo Returns (Part 1)",
        "MC: none\nTeams: Team Kim Seok-jin (V, Suga, & Jin) Team J-Hope (J-Hope, Jimin, Jungkook, & RM)\nBTS play numerous song-related games in the same vein as their previous variety show, BTS Gayo. Team J-Hope wins the first two rounds of Gayo",
        1,
        "https://www.youtube.com/embed/",
        "2019-11-05",
        2
    ),
    (
        "Run BTS! EP.91: BTS Gayo Returns (Part 2)",
        "MC: none\nTeams: Team Kim Seok-jin (V, Suga, & Jin) Team J-Hope (J-Hope, Jimin, Jungkook, & RM)\nBTS continue playing song-related games. Team J-Hope wins. V wins the repechage and is exempted from the penalty. Jin and Suga must wear a trendy item to the airport",
        1,
        "https://www.youtube.com/embed/",
        "2019-11-12",
        2
    ),
    (
        "Run BTS! EP.92: Mini Golden Bell (Part 1)",
        "MC: V\nTeams: none\nBTS compete against each other in quizzes. Jin and Jimin win the first game.",
        1,
        "https://www.youtube.com/embed/",
        "2020-01-14",
        2
    ),
    (
        "Run BTS! EP.93: Mini Golden Bell (Part 2)",
        "MC: V\nTeams: none\nBTS continue competing against each other in quizzes. Jungkook wins. J-Hope receives a penalty. As the privilege of being the MC, V is awarded the ability to take another member with him when he receives a punishment in the future.",
        1,
        "https://www.youtube.com/embed/",
        "2020-01-21",
        2
    ),
    (
        "Run BTS! EP.94: BTS Marble (Part 1)",
        "MC: none\nTeams: Yellow Team (Suga, J-Hope, Jimin, & Jungkook) Blue Team (RM, Jin, & V)\nBTS play the board game BTS Marble.",
        1,
        "https://www.youtube.com/embed/",
        "2020-01-28",
        2
    ),
    (
        "Run BTS! EP.95: BTS Marble (Part 2)",
        "MC: none\nTeams: Yellow Team (Suga, J-Hope, Jimin, & Jungkook) Blue Team (RM, Jin, & V)\nBTS play the board game BTS Marble. Blue Team wins.\n\n\nJ-Hope, Jin, and Suga carry out their punishment from episodes 90 and 92 by wearing sunflower headbands at the airport upon returning to Korea.",
        1,
        "https://www.youtube.com/embed/",
        "2020-02-04",
        2
    ),
    (
        "Run BTS! EP.96: Let's Play With BTS (Part 1)",
        "MC: Jin\nTeams: none\nBTS play classic childhood games and eat snacks from their childhood",
        1,
        "https://www.youtube.com/embed/",
        "2020-03-10",
        2
    ),
    (
        "Run BTS! EP.97: Let's Play With BTS (Part 2)",
        "MC: Jin\nTeams: none\nBTS continue playing classic childhood games. Jimin wins.",
        1,
        "https://www.youtube.com/embed/",
        "2020-03-17",
        2
    ),
    (
        "Run BTS! EP.98: Pajama Party (Part 1",
        "MC: none\nTeams: none\nBTS play various games at a pajama party. Jimin receives a penalty because he is the last one to get dressed.",
        1,
        "https://www.youtube.com/embed/",
        "2020-03-24",
        2
    ),
    (
        "Run BTS! EP.99: Pajama Party (Part 2",
        "MC: none\nTeams: none\nBTS continue playing games at a pajama party. Jin wins. RM places last and has to do the penalty with Jimin.\n\n\nThe penalty is carried out in episode 117.",
        1,
        "https://www.youtube.com/embed/",
        "2020-03-31",
        2
    ),
    (
        "Run BTS! EP.100: Florists",
        "MC: none\nTeams: Bubble Bowl (Jimin) Bouquet (J-Hope & Jungkook) Flower Coronet (RM & Jin) Wreath (Suga & V)\nBTS members are introduced to floristry. A guest florist reveals the birth flower of each of the members and teaches them how to make boutonni\u00e8res. The members then create various flower arrangements of their own design.\n\n\nThis is the final episode to use Idol as the opening theme.",
        1,
        "https://www.youtube.com/embed/",
        "2020-04-07",
        2
    ),
    (
        "Run BTS! EP.101: 100th Episode Special (Part 1",
        "MC: none\nTeams: Team Baek-jin (J-Hope, RM, & Suga) Team Seok-baek (Jungkook, V, Jin, & Jimin)\nTo celebrate the show's 100th episode, BTS members do upgraded versions of missions they enjoyed doing in previous episodes. The members play a quiz about previous Run BTS episodes to determine who will be given the privilege to choose his group members\n\n\nThis is the first episode to use On as the opening theme.",
        1,
        "https://www.youtube.com/embed/",
        "2020-04-14",
        2
    ),
    (
        "Run BTS! EP.102: 100th Episode Special (Part 2)",
        "MC: none\nTeams: Team Baek-jin (J-Hope, RM, & Suga) Team Seok-baek (Jungkook, V, Jin, & Jimin)\nTo celebrate the show's 100th episode, BTS members do upgraded versions of missions they enjoyed doing in previous episodes Team Seok-baek wins.",
        1,
        "https://www.youtube.com/embed/",
        "2020-04-21",
        2
    ),
    (
        "Run BTS! EP.103: King of Avatar Cook (Part 1)",
        "MC: J-Hope\nTeams: Team Kim Seok-yi-gin (Jin, V, & Jungkook) Team Kim Seok-jin (Suga, RM, & Jimin)\nBTS members in each team cook food based on instructions given from team leaders Jin and Suga, who are watching from a separate room",
        1,
        "https://www.youtube.com/embed/",
        "2020-04-28",
        2
    ),
    (
        "Run BTS! EP.104: King of Avatar Cook (Part 2)",
        "MC: J-Hope\nTeams: Team Kim Seok-yi-gin (Jin, V, & Jungkook) Team Kim Seok-jin (Suga, RM, & Jimin)\nBTS members in each team cook food based on instructions given from team leaders Jin and Suga, who are watching from a separate room. Team Kim Seok-yi-gin wins. Team Kim Seok-jin is given the penalty of climbing Achasan mountain\n\n\nThis was the last episode aired before the show went on its first hiatus of the year, for the release of BTS' Break the Silence documentary.",
        1,
        "https://www.youtube.com/embed/",
        "2020-05-05",
        2
    ),
    (
        "Run BTS! Special Episode: Survival Director's cu",
        "MC: none\nTeams: none\nA 16-minute long Director's cut of the survival game BTS played during episode 102 100th Episode Special (Part 2)",
        1,
        "https://www.youtube.com/embed/",
        "2020-05-29",
        2
    ),
    (
        "Run BTS! EP.105: Photo Exhibition (Part 1)",
        "MC: none\nTeams: none\nThe members select various clothing items to remake into an outfit of their own design, then draw lots to decide who will wear which outfit. After doing their own hair and makeup, they must take individual, unit, and group photos and vote for the best one; the winner will receive a prize. Suga wins the musical chairs challenge and gets to choose an outfit first",
        1,
        "https://www.youtube.com/embed/",
        "2020-06-16",
        2
    ),
    (
        "Run BTS! EP.106: Photo Exhibition (Part 2)",
        "MC: none\nTeams: none\nBTS complete their outfits and draw lots to decide which member will wear which one, then model for individual photoshoots based on an assigned theme. Those not being photographed act as support staff during each shoot",
        1,
        "https://www.youtube.com/embed/",
        "2020-06-23",
        2
    ),
    (
        "Run BTS! EP.107: Photo Exhibition (Part 3",
        "MC: none\nTeams: none\nThe members complete their individual photoshoots, then proceed to do unit and group photoshoots. Afterwards, they hold a photo exhibition to evaluate the individual photos. Suga's photo of Jungkook is selected as the winner; Suga receives a framed photo of Jimin photographed by Jungkook as his prize.",
        1,
        "https://www.youtube.com/embed/",
        "2020-06-30",
        2
    ),
    (
        "Run BTS! EP.108: BTS Game Scouts (Part 1)",
        "MC: none\nTeams: none\nBTS compete against each other in a series of video games at an Esports arena. The overall winner will receive a prize",
        1,
        "https://www.youtube.com/embed/",
        "2020-07-07",
        2
    ),
    (
        "Run BTS! EP.109: BTS Game Scouts (Part 2)",
        "MC: none\nTeams: none\nBTS continue playing video games. Jungkook wins and receives  ₩500,000 in gift certificates",
        1,
        "https://www.youtube.com/embed/",
        "2020-07-14",
        2
    ),
    (
        "Run BTS! EP.110: Dubbing",
        "MC: none\nTeams: none\nBTS dub short scenes from The Lion King, Toy Story, and Zootopia, under the supervision of voice actor Ahn Ji-hwan in a recording studio",
        1,
        "https://www.youtube.com/embed/",
        "2020-07-21",
        2
    ),
    (
        "Run BTS! EP.111: Treasure Hunt (Part 1)",
        "MC: none\nTeams: none\nBTS play games as a team to win hints for a treasure hunt at Hyundai Motor Studio",
        1,
        "https://www.youtube.com/embed/",
        "2020-07-28",
        2
    ),
    (
        "Run BTS! EP.112: Treasure Hunt (Part 2)",
        "MC: none\nTeams: none\nThe members play individually to find clues for the hidden treasure. The treasure is going home early Jin is the first one to finish.\n\n\nThis was the last episode aired before the show went on its second (and final) hiatus of the year, for the release of the BTS In the Soop reality series.",
        1,
        "https://www.youtube.com/embed/",
        "2020-08-04",
        2
    ),
    (
        "Run BTS! Special Episode: Dubbing Director's Cut",
        "MC: none\nTeams: none\nIn an extended version of episode 110, BTS dub over the short film Dalbang Dorm (\ub2ec\ubc29\ud558\uc219, RR: Dalbanghasuk) created in episodes 74-77.",
        1,
        "https://www.youtube.com/embed/",
        "2020-08-11",
        2
    ),
    (
        "Run BTS! EP.113: Dalbang School (Part 1)",
        "MC: Jin\nTeams: V Team (RM & J-Hope) Bear Team (V & Suga) Hyuk Team  (Jungkook & Jimin)\nBTS divide into teams and must pass different school subjects. They compete in Korean and Art classes",
        1,
        "https://www.youtube.com/embed/",
        "2020-10-20",
        2
    ),
    (
        "Run BTS! EP.114: Dalbang School (Part 2)",
        "MC: Jin\nTeams: V Team (RM & J-Hope) Bear Team (V & Suga) Hyuk Team  (Jungkook & Jimin)\nBTS divide into teams and must pass different school subjects. They compete in Music, Chinese, and P.E class. V Team wins. Hyuk Team has to wear a spangle T-shirt made by the staff. As the privilege of being the MC, Jin is awarded the ability to take another member with him when he receives a punishment in the future.",
        1,
        "https://www.youtube.com/embed/",
        "2020-10-27",
        2
    ),
    (
        "Run BTS! EP.115: League of Number One (Part 1)",
        "MC: none\nTeams: Team  A (RM, Suga, Jimin, Teddy, Faker & Cuzz) Team B (Jungkook, Jin, J-Hope, V, Effort & Canna)\nBTS and T1 play various games such as I am ground and Toy Hammer Game at the start as an icebreaker, then divide into groups to sing a BTS song and play Mundo Dodgeball & What The Box?",
        1,
        "https://www.youtube.com/embed/",
        "2020-11-03",
        2
    ),
    (
        "Run BTS! EP.116: League of Number One (Part 2)",
        "MC: none\nTeams: Team  A (RM, Suga, Jimin, Teddy, Faker & Cuzz) Team B (Jungkook, Jin, J-Hope, V, Effort & Canna)\nBTS and T1 play various computer games such as Gang Beasts & Fall Guys at an e-sports arena Both teams tie.",
        1,
        "https://www.youtube.com/embed/",
        "2020-11-10",
        2
    ),
    (
        "Run BTS! EP.117: Teambuilding Special (Part 1)",
        "MC: none\nTeams: none\nBTS do teamwork challenges and have to complete five out of sixteen to go home.\n\n\nRM and Jimin carry out their penalty from episodes 98-99 by wearing work pants and rubber shoes.",
        1,
        "https://www.youtube.com/embed/",
        "2020-11-17",
        2
    ),
    (
        "Run BTS! EP.118: Teambuilding Special (Part 2)",
        "MC: none\nTeams: none\nBTS have to complete at least five out of sixteen teamwork challenges in order to go home for the day. They successfully complete five challenges and go home early.",
        1,
        "https://www.youtube.com/embed/",
        "2020-11-24",
        2
    ),
    (
        "Run BTS! EP.119: Photo Story (Part 1)",
        "MC: none\nTeams: none\nAt Samsung Electronics Cafe Camptong, BTS need to find sticky notes and take pictures according to the instructions written on them to earn points. They must also locate seven key cards that open lockers with more sticky notes inside each card is worth 10 points. As a penalty, the member with the least points must act as a Genie to the member with the most points and grant him a wish.\n\n\nJimin and Jungkook carry out their punishment from episode 114 by wearing spangled t-shirts for the day.",
        1,
        "https://www.youtube.com/embed/",
        "2020-12-01",
        2
    ),
    (
        "Run BTS! EP.120: Photo Story (Part 2)",
        "MC: none\nTeams: none\nThe members review each other's photos to determine the winner. Jin is revealed as a spy points are deducted from the other members for every picture in which any part of his body appears. V wins with 33 points. Jin receives a special benefit for successfully carrying out his spy mission. Jungkook scores the lowest with only 7 points and must grant V a wish as the Genie.",
        1,
        "https://www.youtube.com/embed/",
        "2020-12-08",
        2
    ),
    (
        "Run BTS! EP.121: Reply BTS Village (Part 1)",
        "MC: none\nTeams: Detective (Jin) Innocents (Suga, J-Hope, Jimin, & Jungkook) Culprits (RM, V)\nBTS play a modified version of Mafia, set in the BTS Village during the 1900s: the members act as former residents of BTS Village with the goal of finding who among them broke the ARMY headstone.\n\n\nEpisodes set in BTS Village make up the BTS Village universe (as explained in episode 146). Reply BTS Village is preceded by Season 2's Protect the BTS Village (episodes 48-49), and followed by Season 3's BTS Village: Joseon Dynasty (episodes 146-148).",
        1,
        "https://www.youtube.com/embed/",
        "2020-12-15",
        2
    ),
    (
        "Run BTS! EP.122: Reply BTS Village (Part 2)",
        "MC: none\nTeams: Detective (Jin) Innocents (Suga, J-Hope, Jimin, & Jungkook) Culprits (RM, V)\nBTS play a modified version of Mafia, set in the BTS Village during the 1900s: the members act as former residents of BTS Village with the goal of finding who among them broke the ARMY headstone. Culprits win. Jungkook, despite being an innocent villager, is given a last chance and correctly guesses the Culprits identities. He does not receive the punishment.",
        1,
        "https://www.youtube.com/embed/",
        "2020-12-22",
        2
    ),
    (
        "Run BTS! EP.123: Reverse Avatar Cook (Part 1)",
        "MC: RM\nTeams: Avatar Cooks (Jin & Suga) Team 1 (J-Hope & V) Team 2 (Jimin & Jungkook)\nA reverse version of Episode 103-104: King of Avatar Cook, BTS members in each team give instructions to Jin and Suga based on a recipe video tutorial while they monitor the duo's cooking progress in a separate room.",
        1,
        "https://www.youtube.com/embed/",
        "2020-12-29",
        2
    ),
    (
        "Run BTS! EP.124: Reverse Avatar Cook (Part 2)",
        "MC: RM\nTeams: Avatar Cooks (Jin & Suga) Team 1 (J-Hope & V) Team 2 (Jimin & Jungkook)\nA reverse version of Episode 103-104: King of Avatar Cook, BTS members in each team give instructions to Jin and Suga based on a recipe video tutorial while they monitor the duo's cooking progress in a separate room. Team 2 wins. Team 1 has to wear a spangle T-shirt. As the privilege of being the MC, RM is awarded the ability to take another member with him when he receives a punishment in the future.",
        1,
        "https://www.youtube.com/embed/",
        "2021-01-05",
        2
    ),
    (
        "Run BTS! EP.125: Producer Special",
        "MC: none\nTeams: none\nBTS members become part of the show's production staff for the day. During the first group meeting, after writing down their ideas, the members take turns presenting their ideas to each other and the rest of the staff. During the second group meeting, the members develop plans for one short-term and one long-term project using the approved ideas (chosen by the staff) from the previous meeting.",
        1,
        "https://www.youtube.com/embed/",
        "2021-01-12",
        2
    ),
    (
        "Run BTS! EP.126: K-HAM Special",
        "MC: none\nTeams: Team 1  (V, Jimin, & Jin) Team 2 (Jungkook, RM, & J-Hope)\nBTS divide into two teams of three and prepare dishes using k-ham (canned pork) that will be judged by South Korean chef Baek Jong-won. The winning team will receive special knives engraved with Baek's name as a prize. Team 1 cooks ham potato stew. Team 2 cooks ramen, ham and rice. Baek shows BTS how to make ham fried rice in return. At the end of the episode, Baek announces that both teams won because they both made their dishes well, and presents knives to all seven members.\n\n\nThe episode is a collaboration between Baek and BTS to promote Korean pork. A condensed version of the special was aired on episode 59 of Baek's SBS TV reality cuisine show, Delicious Rendezvous, on January 28, 2021.",
        1,
        "https://www.youtube.com/embed/",
        "2021-01-19",
        2
    ),
    (
        "Run BTS! EP.127: 777 Lucky Seven (Part 1)",
        "MC: none\nTeams: none\nThe members must complete 14 challenges in order to go home.\n\n\nJ-Hope and V carry out their punishment from episode 124 by wearing spangled t-shirts.",
        1,
        "https://www.youtube.com/embed/",
        "2021-01-26",
        2
    ),
    (
        "Run BTS! EP.128: 777 Lucky Seven (Part 2)",
        "MC: none\nTeams: none\nSuga is the first to complete all challenges. V is unable to complete the final dominoes challenge and finishes last but is allowed to go home.",
        1,
        "https://www.youtube.com/embed/",
        "2021-02-02",
        2
    ),
    (
        "Run BTS! EP.129: Hello 2021",
        "MC: none\nTeams: none\nBTS play three indoor games. They will be randomly penalized according to how well or poorly the other members play. The first is the Liar Game. Jungkook wins, Jin receives the penalty. For the second game, BTS must correctly identify the title of their song being played on the harmonica by one of the members. Jungkook scores the most points. RM, Jin, Jimin, and V share the penalty the last two lose. The final game is a cushion version of Red Light, Green Light. RM and V lose, but the latter is selected as the day's MVP. The members give closing comments on their hopes for the new year, and RM and V carry out their penalty.",
        1,
        "https://www.youtube.com/embed/",
        "2021-02-09",
        2
    ),
    (
        "Run BTS! EP.130: Long-term Project Tennis",
        "MC: none\nTeams: Jungkook, Suga, & Jin V, Jimin, RM, & J-Hope.\nBTS begin their long-term project, Tennis. Former members of the Korean national team, Im Kyu-tae and Kwon Soon-woo, appear as guest coaches in the first half of the episode. BTS split into two groups of three (Jungkook, Suga, Jin) and four (V, Jimin, RM, J-Hope) Im teaches the former the forehand swing, Kwon teaches the latter the backhand swing. The groups switch coaches to learn the other swing, then play a short practice game against each other. Jungkook, Suga, Jin, and Kwon win. The rest of the episode consists of footage of the members taking tennis lessons at a professional center in the weeks following.",
        1,
        "https://www.youtube.com/embed/",
        "2021-02-16",
        2
    ),
    (
        "Run BTS! EP.131: Long-term Project Tennis 2",
        "MC: Suga\nTeams: none\nUsing their recently acquired tennis skills, BTS compete against each other in a tennis tournament, BTS Tennis Championship, refereed by tennis coach Kim Sang-hyun. Suga does not participate in the competition, but serves as MC and as a commentator alongside Kim. Jin wins both of his matches (10-6 against Jimin in the semi-final, 7-3 against V in the final) and the tournament. He receives a gold medal. The members eat dinner together at a Chinese restaurant to celebrate.",
        1,
        "https://www.youtube.com/embed/",
        "2021-02-23",
        2
    ),
    (
        "Run BTS! EP.132: 77 Minute Debate (Part 1)",
        "MC: none\nTeams: none\nBTS engage in a 77-minute debate on seven different topics at a hotel pool; each round lasts 11 minutes. They all write Run BTS on their palms and the member with the clearest remaining writing at the end of the day will win a certificate for the hotel.",
        1,
        "https://www.youtube.com/embed/",
        "2021-03-02",
        2
    ),
    (
        "Run BTS! EP.133: 77 Minute Debate (Part 2)",
        "MC: none\nTeams: none\nBTS complete the final four debate topics. Jimin is declared the winner.",
        1,
        "https://www.youtube.com/embed/",
        "2021-03-09",
        2
    ),
    (
        "Run BTS! EP.134: Workshop Special (Part 1)",
        "MC: none\nTeams: none\nBTS does three programs: Search King, Guess This Dance, and Protect My Belongings. Jimin wins Search King.",
        1,
        "https://www.youtube.com/embed/",
        "2021-03-16",
        2
    ),
    (
        "Run BTS! EP.135: Workshop Special (Part 2)",
        "MC: none\nTeams: none\nThe Guess This Dance challenge is next. Jungkook wins.",
        1,
        "https://www.youtube.com/embed/",
        "2021-03-23",
        2
    ),
    (
        "Run BTS! EP.136: Workshop Special (Part 3)",
        "MC: none\nTeams: none\nProtect My Belongings is the final challenge. Jungkook and J-Hope win. As a penalty, Jimin has to make lunch for himself, RM, and Suga, for their climb up Achasan mountain.",
        1,
        "https://www.youtube.com/embed/",
        "2021-03-30",
        2
    ),
    (
        "Run BTS! EP.137: Entertainment Quiz Show (Part 1)",
        "MC: none\nTeams: Team Jimin and Jungkook (Jimin & Jungkook) Team 1, 2, 3, Fighting (RM & V) Team J-Hope awesome Jin (Jin & J-Hope)\nBTS split into three teams and play a quiz show. There are three main categories: nonsense questions, beeper code quiz, and Dialect quiz. The teams receive prizes based on the number of points they score.",
        1,
        "https://www.youtube.com/embed/",
        "2021-04-06",
        2
    ),
    (
        "Run BTS! EP.138: Entertainment Quiz Show (Part 2)",
        "MC: none\nTeams: Team Jimin and Jungkook (Jimin & Jungkook) Team 1, 2, 3, Fighting (RM & V) Team J-Hope awesome Jin (Jin & J-Hope)\nBTS play several games related to guessing music from the past and present next. Jungkook and V end up using phone call chances. Team J-Hope awesome Jin wins.",
        1,
        "https://www.youtube.com/embed/",
        "2021-04-13",
        2
    ),
    (
        "Run BTS! EP.139: BTS Table Tennis Class (Part 1)",
        "MC: none\nTeams: none\nBTS members practice table tennis with You Seung Min",
        1,
        "https://www.youtube.com/embed/",
        "2021-04-20",
        2
    ),
    (
        "Run BTS! EP.140: BTS Table Tennis Class (Part 2)",
        "MC: none\nTeams: none\nThe episode continues with the members competing against each other in a table tennis tournament. V wins (after besting Jungkook in the first round, Jimin in the semi-final round, and J-Hope in the final round). Jin loses the final match against Jungkook and has to clean up.",
        1,
        "https://www.youtube.com/embed/",
        "2021-04-27",
        2
    ),
    (
        "Run BTS! EP.141: BTS Collaboration Variety Show (Part 1)",
        "MC: Na Young-seok\nTeams: none\nIn a collaboration between Run BTS and TV producer-director Na Young-seok's The Game Caterers, BTS members take on challenges and missions akin to the popular variety shows Na has produced.",
        1,
        "https://www.youtube.com/embed/",
        "2021-05-04",
        2
    ),
    (
        "Run BTS! EP.142: BTS Collaboration Variety Show (Part 2)",
        "MC: Na Young-seok\nTeams: none\nIn a collaboration between Run BTS and TV producer-director Na Young-seok's The Game Caterers, BTS members take on challenges and missions akin to the popular variety shows Na had produced. Jimin wins. In the end, the members receive gifts from Game Caterers.\n\n\nThis is the final episode to use On as the opening theme. The show went on a month-long hiatus after this episode in order to accommodate promotions for the band's new single at the time, Butter, followed by their eighth anniversary celebrations.",
        1,
        "https://www.youtube.com/embed/",
        "2021-05-11",
        2
    ),
    (
        "Run BTS! EP.143: Perfect Pairings",
        "MC: Baek Jong-won\nTeams: Team Green Onion (J-Hope, RM & Jimin) Team Napa Cabbage (V, Jin & Jungkook)\nChef Baek Jong-won returns to oversee a cooking challenge. BTS divide into two groups of three and must each cook a dish using kimchi. Team Napa Cabbage makes kimchi and sujebi while Team Green Onion makes green onion kimchi and jjajang ramyeon.\n\n\nThis is the first episode to use Butter as the opening theme.",
        1,
        "https://www.youtube.com/embed/",
        "2021-06-15",
        2
    ),
    (
        "Run BTS! EP.144: BTS Books",
        "MC: none\nTeams: V & J-Hope Jungkook & Jin Jimin & RM\nBTS write children's stories. All teams win. Suga has to write book reports on the stories.",
        1,
        "https://www.youtube.com/embed/",
        "2021-06-22",
        2
    ),
    (
        "Run BTS! EP.145: RUN BTS Gayo",
        "MC: TBA\nTeams: TBA\nBTS participate in three rounds of quizzes about their songs: the consonant quiz, picture speed quiz, and songs based on ARMY's choice. V is named the episode's MVP.",
        1,
        "https://www.youtube.com/embed/",
        "2021-06-29",
        2
    ),
    (
        "Run BTS! EP.146: BTS Village: Joseon Dynasty 1",
        "MC: none\nTeams: Thieves (unknown) Citizens (unknown)\nBTS play a Mafia-treasure hunt hybrid game in the BTS Village, now set in the Joseon Dynasty. The members act as Joseon-era residents of the village and have to find the missing piece of the broken (in episode 121) ARMY headstone to return to 2021. They must correctly guess who among them are the Thieves trying to distract them in their search, and avoid being caught by the royal army or receive a penalty. Clues to the location of the missing piece are hidden throughout the village. Each member is additionally given an individual mission to carry out and can receive a superpower to aid their search if they successfully complete it. The game comprises two rounds. The losing team will be flogged by the winning team.\n\n\nEpisodes set in BTS Village make up the BTS Village universe (as explained in this episode). BTS Village: Joseon Dynasty is preceded by Season 2's Protect the BTS Village (episodes 48-49), and Season 3's Reply BTS Village (episodes 121-122).",
        1,
        "https://www.youtube.com/embed/",
        "2021-08-03",
        2
    ),
    (
        "Run BTS! EP.147: BTS Village: Joseon Dynasty 2",
        "MC: none\nTeams: Thieves (unknown) Citizens (unknown)\nBTS play a Mafia-treasure hunt hybrid game in the BTS Village, set in the Joseon Dynasty. With some prompting from the staff, BTS successfully locate the first hint to the location of the missing headstone piece and complete round one. The searchable game area expands and round two begins. The members locate more clues and try to decipher their meaning, while their suspicions of one another other grow. RM figures out that there must be at least three Thieves among them.",
        1,
        "https://www.youtube.com/embed/",
        "2021-08-10",
        2
    ),
    (
        "Run BTS! EP.148: BTS Village: Joseon Dynasty 3",
        "MC: none\nTeams: Thieves (Jin & Suga) Citizens (J-Hope, RM, Jimin, Taehyung & Jungkook)\nBTS play a Mafia-treasure hunt hybrid game in the BTS Village, set in the Joseon Dynasty. They locate the headstone piece hidden in the clothes of a prisoner mannequin in one of the jail cells, and review collected clues to eliminate the members suspected of being Thieves Suga, Jin, and V are chosen. After lengthy deliberation, Jimin, J-Hope, RM, and Jungkook successfully raise the headstone and return to 2021. Jin and Suga reveal themselves as the Thieves the staff confirm there were only two the entire time and that V was an innocent villager. For their penalty, they are each hit once with a thick wooden rod (the gonjang, a Joseon-era form of punishment) by V and Jungkook respectively.",
        1,
        "https://www.youtube.com/embed/",
        "2021-08-17",
        2
    ),
    (
        "Run BTS! EP.149: Bangtan Interior Design 1",
        "MC: none\nTeams: Jin team (Jin, J-Hope, RM & V) Suga team (Suga, Jungkook & Jimin)\nBTS try out interior design. They divide into two teams and must complete one of two prepared room concepts. They play several quizzes to decide which team will choose first the winning team will receive help from the staff. Suga team wins and selects Interior A (soft grey), Jin team gets Interior B (dark blue). Each team must paint and decorate a 4m \u00d7 4m room, and furnish it with furniture they have assembled themselves.",
        1,
        "https://www.youtube.com/embed/",
        "2021-08-24",
        2
    ),
    (
        "Run BTS! EP.150: Bangtan Interior Design 2",
        "MC: none\nTeams: Jin team (Jin, J-Hope, RM & V) Suga team (Suga, Jungkook & Jimin)\nBTS try out interior design. Both teams finish preparing their rooms and the staff vote for the best one. Suga team wins.",
        1,
        "https://www.youtube.com/embed/",
        "2021-08-31",
        2
    ),
    (
        "Run BTS! EP.151: War of Money Staycation, 1",
        "MC: none\nTeams: none\nBTS go on a staycation at Josun Palace Hotel in Gangnam. They play games to determine individual room assignments Jimin ends up with the smallest room. The members are provided with special room-service menus, a credit card with an unknown limit, and given a mission: they can order anything from the menu (two items per person), but must do so in the order they went into their rooms, and without knowing what the food budget is. The mission will end when they either bring the card balance down to zero, or exceed the limit. If they achieve the former, they will receive  ₩7 million in prize money to be divided equally among themselves.",
        1,
        "https://www.youtube.com/embed/",
        "2021-09-07",
        2
    ),
    (
        "Run BTS! EP.152: War of Money Staycation, 2",
        "MC: none\nTeams: none\nBTS order exactly  ₩8.01 million worth of food and games for the mission, then spend the rest of their time relaxing alone and with each other. At the end of the episode, the staff reveal that they correctly guessed the budget and award them the prize money.",
        1,
        "https://www.youtube.com/embed/",
        "2021-09-14",
        2
    ),
    (
        "Run BTS! EP.153: Throwback Songs 1",
        "MC: none\nTeams: none\nBTS play song guessing games and are given the opportunity to reset all penalties accrued from past episodes that have not yet been carried out. They guess the titles of old cartoon theme songs based on a brief musical excerpt, and play Metal Tray Karaoke: two songs are mixed together and they must correctly sing the corresponding part and lyrics of the entire mix. If they get it wrong, an aluminum tray will be dropped on their head. The day's loser will have to cross the skybridge of Lotte World Tower (541m high), accompanied by a member of his choosing.",
        1,
        "https://www.youtube.com/embed/",
        "2021-09-21",
        2
    ),
    (
        "Run BTS! EP.154: Throwback Songs 2",
        "MC: none\nTeams: none\nJ-Hope is the runner-up and wins a penalty exemption. Suga places last, and RM volunteers to accompany him to Lotte World Tower. While crossing the skybridge, they stop halfway to perform the choreography for Permission to Dance together.",
        1,
        "https://www.youtube.com/embed/",
        "2021-09-28",
        2
    ),
    (
        "Run BTS! EP.155: Finale (Part 1)",
        "MC: Jin\nTeams: none\nBTS revisit various episodes in the show's history and must guess which ones are the highest-ranked as voted by fans.",
        1,
        "https://www.youtube.com/embed/",
        "2021-10-05",
        2
    ),
    (
        "Run BTS! EP.156: Finale (Part 2)",
        "MC: none\nTeams: none\nBTS play games (photozone and debate) from past episodes of the show and reminisce about old memories.",
        1,
        "https://www.youtube.com/embed/",
        "2021-10-12",
        2
    ),
    (
        "Run BTS! Special Episode: Telepathy Part 1",
        "MC: none\nTeams: none\nReunited after a 10-month break, BTS play a series of telepathy games to test how in tune with each other they still are. They play two guessing games in the filming studio. For the third game, they are put into separate cars, given a keyword (Real fun), and must visit a place based on the keyword that they think the other members would go to. The game comprises two rounds and the first ends when they each arrive at their destination. To successfully carry out the mission, all seven members must end up in the same place. V, Jin, Jimin, and RM head to Nonhyeon-dong; J-Hope goes to Jamsil Olympic Stadium; Suga goes to Jamwon Hangang Park; Jungkook goes to Lotte World.",
        1,
        "https://www.youtube.com/embed/",
        "2022-08-16",
        2
    ),
    (
        "Run BTS! Special Episode: Telepathy Part 2",
        "MC: none\nTeams: none\nJimin, RM, Jin, V, and Jungkook meet up at their old Blue Dorm in the second round the keyword was Salty and they all headed to a place where they had several memorable fights in the past. Suga and J-Hope head to their first dorm and the restaurant next to their old practice room, but are unable to meet each other. In the third round, the staff let the members decide the keywords themselves and Suga runs into J-Hope who still has not left his previous destination. They figure out the location of the others and reunite with them at Han River Park. The final keyword given is ARMY. Six of the members head to Jamsil Olympic Stadium while V goes to Ilji Art Hall, the venue of their first concert. At the end of the episode, the septet have a meal together and discuss ideas for future episodes.",
        1,
        "https://www.youtube.com/embed/",
        "2022-08-23",
        2
    ),
    (
        "Run BTS! Special Episode: Fly BTS Fly Part 1",
        "MC: none\nTeams: none\nBased on their discussion at the end of the Telepathy special, BTS try aerial yoga for the first time. An instructor teaches the members various beginner positions and they must have the best possible photos taken of themselves in any of the poses learned to post on social media.",
        1,
        "https://www.youtube.com/embed/",
        "2022-10-11",
        2
    ),
    (
        "Run BTS! Special Episode: Fly BTS Fly Part 2",
        "MC: none\nTeams: none\nBTS learn more aerial yoga positions then select one pose they each like best and take individual photos. Jimin goes first, followed by Jin, then Jungkook, Suga, J-Hope, RM, and V. After successfully taking usable photos, the staff inform them that unit photos are next. The instructor demonstrates duo positions with Jimin then the pairs (J-Hope and Jungkook, Suga and RM, Jin and V) replicate the poses and take their photos. Jimin and Jungkook are selected to pose together for a final duo photo as the ace team. Per the members request, the instructor teaches them the Bat position, following which the episode ends with them posing for a group photo to be used as the episode's video thumbnail upside down.",
        1,
        "https://www.youtube.com/embed/",
        "2022-10-18",
        2
    ),
    (
        "Run BTS! Special Episode: 'RUN BTS TV' On-air Part 1",
        "MC: none\nTeams: none\nBTS assume the role of both content creators and audience viewers in the BTS Dalbang TV Special. The members launch individual media channels by preparing and presenting a live show of their choosing. During each broadcast, the remaining six members act as viewers and watch the show from a separate set designed to mimic a home-viewing experience. The presenter must interact with and keep the attention of the viewers while engaging in his selected activity. The viewers can post comments in a live chatroom for the presenter to see. Jungkook learns to play Butter on the drums with a guest teacher; Suga takes painting requests; Jin plays online games; J-Hope unboxes children's toys.",
        1,
        "https://www.youtube.com/embed/",
        "2022-11-22",
        2
    ),
    (
        "Run BTS! Special Episode: 'RUN BTS TV' On-air Part 2",
        "MC: none\nTeams: none\nJ-Hope finishes his show. V plays screen golf; RM answers a series of nonsensical questions; Jimin does a mukbang.",
        1,
        "https://www.youtube.com/embed/",
        "2022-11-29",
        2
    ),
    (
        "Run BTS! Special Episode: Next Top Genius Part 1",
        "MC: none\nTeams: none\nBTS participate in a psychological and brain competition. They play a number card game first. Jimin wins. Next is the Cat ears O,X liar game, during which the members all wear electroencephalographic cat ears. A question is sent via cellphone to five Villagers while a liar message is sent to two Liars. All seven must answer the question, without it being revealed aloud, by raising an O or X paddle in agreement/disagreement. The Villagers must then correctly identify the Liars at the end of each round in order to win the game. The Villagers eventually win.",
        1,
        "https://www.youtube.com/embed/",
        "2023-01-03",
        2
    ),
    (
        "Run BTS! Special Episode: Next Top Genius Part 2",
        "MC: none\nTeams: none\nBTS play three more games: I Object, Yes or No, and Hopscotch-Rock paper scissors. Suga wins I Object, Jimin and V win Yes or No, Jimin wins Hopscotch-Rock paper scissors.",
        1,
        "https://www.youtube.com/embed/",
        "2023-01-10",
        2
    ),
    (
        "Run BTS! Special Episode: Mini Field Day Part 1",
        "MC: none\nTeams: none\nBTS participate in a mini field day similar to the Idol Star Athletics Championships (ISAC). Four games will be played and the person who accumulates the most points overall will be the day's winner. Soft Fencing is first, V wins. Volleyball is next, Jungkook wins.",
        1,
        "https://www.youtube.com/embed/",
        "2023-02-14",
        2
    ),
    (
        "Run BTS! Special Episode: Mini Field Day Part 2",
        "MC: none\nTeams: none\nBTS play the final two games for their field day. First is weightlifting with ping pong balls; V wins. Next is Slippery Soccer. They divide into two teams: Red (Jin, Jungkook, V) and Blue (Jimin, J-Hope, RM, Suga); the game ends in a draw. At the medal ceremony, V receives gold as the day's overall winner; Jungkook receives silver; J-Hope receives bronze. Jin also receives a medal as the day's MVP and hidden first place winner for winning first place on M Countdown with The Astronaut.\n\n\nThis was the final episode filmed before Jin enlisted in December 2022.",
        1,
        "https://www.youtube.com/embed/",
        "2023-02-21",
        2
    );
    
-- inserting Tags
INSERT INTO Tags (tag)
VALUES	("water"),
		("chuseok"),
        ("teams"),
        ("skit"),
		("confession booth"),
        ("paintball"),
        ("treasure hunt"),
		("bungee jumping"),
        ("eating"),
		("school"),
        ("police"),
        ("spy"),
		("snow"),
        ("arcade"),
        ("bowling"),
		("cooking"),
        ("board games"),
        ("dogs"),
		("zombies"),
        ("escape room"),
        ("freeze tag"),
        ("obstacle course"),
        ("MT"),
		("karaoke"),
        ("letters"),
        ("hotel"),
        ("bunny hats"),
        ("sauna"),
        ("debate"),
        ("comics"),
        ("travel"),
        ("mafia"),
        ("acting"),
        ("kdrama"),
        ("scavenger hunt"),
        ("betrayal"),
        ("VR"),
        ("gift exchange"),
        ("quiz"),
        ("variety games"),
        ("pajamas"),
        ("ASMR"),
        ("workshop"),
        ("flowers"),
        ("sports"),
        ("laser tag"),
        ("fashion"),
        ("video games"),
        ("voice acting"),
        ("indoor games"),
        ("guest"),
        ("photos"),
        ("retro"),
        ("chatting"),
        ("planning"),
        ("tennis"),
        ("computer"),
        ("ping pong"),
        ("story writing"),
        ("music quiz"),
        ("historical"),
        ("dress-up"),
        ("interior design"),
        ("relaxing"),
        ("flying yoga"),
        ("streaming"),
        ("new years");
					
-- connect video and tags
INSERT INTO VideoTags (videoID, tagID)
VALUES	(2, (SELECT tagID FROM Tags WHERE tag = "games")),
		(4, (SELECT tagID FROM Tags WHERE tag = "water")),
        (5, (SELECT tagID FROM Tags WHERE tag = "chuseok")),
        (5, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (5, (SELECT tagID FROM Tags WHERE tag = "games")),
        (6, (SELECT tagID FROM Tags WHERE tag = "skit")),
        (6, (SELECT tagID FROM Tags WHERE tag = "confession booth")),
        (7, (SELECT tagID FROM Tags WHERE tag = "skit")),
        (7, (SELECT tagID FROM Tags WHERE tag = "confession booth")),
        (8, (SELECT tagID FROM Tags WHERE tag = "paintball")),
        (8, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (9, (SELECT tagID FROM Tags WHERE tag = "treasure hunt")),
        (10, (SELECT tagID FROM Tags WHERE tag = "bungee jumping")),
        (11, (SELECT tagID FROM Tags WHERE tag = "eating")),
        (11, (SELECT tagID FROM Tags WHERE tag = "spy")),
        (12, (SELECT tagID FROM Tags WHERE tag = "skit")),
        (12, (SELECT tagID FROM Tags WHERE tag = "school")),
        (13, (SELECT tagID FROM Tags WHERE tag = "skit")),
        (13, (SELECT tagID FROM Tags WHERE tag = "police")),
        (14, (SELECT tagID FROM Tags WHERE tag = "water")),
        (14, (SELECT tagID FROM Tags WHERE tag = "games")),
        (14, (SELECT tagID FROM Tags WHERE tag = "spy")),
        (15, (SELECT tagID FROM Tags WHERE tag = "water")),
        (15, (SELECT tagID FROM Tags WHERE tag = "games")),
        (15, (SELECT tagID FROM Tags WHERE tag = "spy")),
        (16, (SELECT tagID FROM Tags WHERE tag = "water")),
        (16, (SELECT tagID FROM Tags WHERE tag = "games")),
        (16, (SELECT tagID FROM Tags WHERE tag = "spy")),
        (17, (SELECT tagID FROM Tags WHERE tag = "snow")),
        (17, (SELECT tagID FROM Tags WHERE tag = "games")),
        (18, (SELECT tagID FROM Tags WHERE tag = "arcade")),
        (18, (SELECT tagID FROM Tags WHERE tag = "games")),
        (19, (SELECT tagID FROM Tags WHERE tag = "arcade")),
        (19, (SELECT tagID FROM Tags WHERE tag = "games")),
        (20, (SELECT tagID FROM Tags WHERE tag = "bowling")),
        (20, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (21, (SELECT tagID FROM Tags WHERE tag = "cooking")),
        (21, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (22, (SELECT tagID FROM Tags WHERE tag = "indoor")),
        (22, (SELECT tagID FROM Tags WHERE tag = "board games")),
        (23, (SELECT tagID FROM Tags WHERE tag = "chuseok")),
        (23, (SELECT tagID FROM Tags WHERE tag = "games")),
        (24, (SELECT tagID FROM Tags WHERE tag = "dogs")),
        (25, (SELECT tagID FROM Tags WHERE tag = "zombies")),
        (25, (SELECT tagID FROM Tags WHERE tag = "escape room")),
        (25, (SELECT tagID FROM Tags WHERE tag = "freeze tag")),
        (26, (SELECT tagID FROM Tags WHERE tag = "video games")),
        (26, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (27, (SELECT tagID FROM Tags WHERE tag = "obstacle course")),
        (27, (SELECT tagID FROM Tags WHERE tag = "teams")),
        (28, (SELECT tagID FROM Tags WHERE tag = "fashion")),
        (28, (SELECT tagID FROM Tags WHERE tag = "MT")),
        (29, (SELECT tagID FROM Tags WHERE tag = "karaoke")),
        (29, (SELECT tagID FROM Tags WHERE tag = "MT")),
        (30, (SELECT tagID FROM Tags WHERE tag = "fashion")),
        (31, (SELECT tagID FROM Tags WHERE tag = "variety games")),
        (32, (SELECT tagID FROM Tags WHERE tag = "variety games")),
        (33, (SELECT tagID FROM Tags WHERE tag = "scavenger hunt")),
        (33, (SELECT tagID FROM Tags WHERE tag = "spy")),
        (34, (SELECT tagID FROM Tags WHERE tag = "photos")),
        (35, (SELECT tagID FROM Tags WHERE tag = "games")),
        (35, (SELECT tagID FROM Tags WHERE tag = "gift exchange")),
        (36, (SELECT tagID FROM Tags WHERE tag = "cooking")),
        (37, (SELECT tagID FROM Tags WHERE tag = "cooking")),
        (28, (SELECT tagID FROM Tags WHERE tag = "board games")),
        (39, (SELECT tagID FROM Tags WHERE tag = "games")),
        (40, (SELECT tagID FROM Tags WHERE tag = "variety games")),
        (41, (SELECT tagID FROM Tags WHERE tag = "new years")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = ""))
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = ""))
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = "")),
        (, (SELECT tagID FROM Tags WHERE tag = ""));
        
-- for starring 1-40 contain all members
-- index.js has link that u can use to insert
-- all members from videos min to max
INSERT INTO Starring (videoID, artistID)
			VALUES	(:video, 1),
					(:video, 2),
					(:video, 3),
					(:video, 4),
					(:video, 5),
					(:video, 6),
					(:video, 7);